[package]
name = "puppet"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.16", features = ["derive"] }
clap_complete = "4.4.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
hyper = { version = "1.2.0", features = ["full"] }
tokio = { version = "1.36.0", features = ["full"] }
reqwest = { version = "0.11.24", features = ["stream"] }
reqwest-eventsource = "0.5.0"
futures = "0.3.30"
rand = "0.8.5"
