[package]
name = "puppet"
version = "0.3.2"
edition = "2021"

[dependencies]
anyhow = "1"
log = "0"
env_logger = "0"
clap = { version = "4", features = ["derive"] }
clap_complete = "4"
serde = { version = "1", features = ["derive", "rc"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0", features = ["stream"] }
bytes = "1"
futures = "0"
rand = "0"
base64 = "0"
uuid = { version = "1", features = ["v4"] }
regex = "1"
glob = "0"
