[package]
name = "puppet"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing = "0"
tracing-subscriber = "0"
clap = { version = "4", features = ["derive"] }
clap_complete = "4"
serde = { version = "1", features = ["derive", "rc"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
reqwest = "0"
rand = "0"
base64 = "0"
uuid = { version = "1", features = ["v4"] }
bytes = "1"
regex = "1"
glob = "0"
